baseURL = 'https://bardman.dev/'
languageCode = 'en-us'
title = "bardman's website"

pygmentsUseClasses = false
pygmentsCodefences = true
pygmentsStyle = "modus-vivendi"
theme = 'lugo'

[menu]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10        

[params]
    relatedtext = "Related"
    favicon = "/favicon.png"

    nextprev = false
    taglist = false
    showrss = true
    timezone = "America/New_York"
    dateFormat = "January 2, 2006"

[markup]
  [markup.org]
    enable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 2

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2